FROM nginx:stable-alpine-perl

WORKDIR "/etc/nginx/"

EXPOSE 80
EXPOSE 443

RUN apk update && \
  apk add --no-cache openssl && \
  apk add --no-cache sed && \
  apk add --no-cache curl && \
  rm -rf /var/cache/apk/*

RUN curl https://get.acme.sh | sh

RUN mkdir /etc/nginx/sites-enabled
RUN mkdir /etc/nginx/ssl
RUN mkdir -p /var/www/letsencrypt

COPY edge/mime_types /etc/nginx/mime_types
COPY edge/nginx.conf /etc/nginx/nginx.conf
COPY edge/sites-enabled/ /etc/nginx/sites-enabled/

COPY edge/start.sh /etc/nginx/start.sh
ENTRYPOINT ["sh", "./start.sh"]